const SONGS = [
  { id: "1", title: "@ MEH", artist: "Playboi Carti", display: "@ MEH - Playboi Carti", clip: "clips/at-meh.mp3" },
  { id: "2", title: "3G", artist: "Lil Uzi Vert & Yeat", display: "3G - Lil Uzi Vert & Yeat", clip: "clips/3G.mp3" },
  { id: "3", title: "13", artist: "Lucki", display: "13 - Lucki", clip: "clips/13.mp3" },
  { id: "4", title: "Back 2 Da Basics", artist: "Summrs", display: "Back 2 Da Basics - Summrs", clip: "clips/back-2-da-basics.mp3" },
  { id: "5", title: "BFO2", artist: "Summrs", display: "BFO2 - Summrs", clip: "clips/bfo2.mp3" },
  { id: "6", title: "Chrome Heart Tags", artist: "Lil Uzi Vert", display: "Chrome Heart Tags - Lil Uzi Vert", clip: "clips/chrome-heart-tags.mp3" },
  { id: "7", title: "Enter The Dragon", artist: "Lancey Foux", display: "Enter The Dragon - Lancey Foux", clip: "clips/enter-the-dragon.mp3" },
  { id: "8", title: "Excuse My French", artist: "Fimiguerrero & Len", display: "Excuse My French - Fimiguerrero & Len", clip: "clips/excuse-my-french.mp3" },
  { id: "9", title: "Get Away", artist: "Osamason", display: "Get Away - Osamason", clip: "clips/get-away.mp3" },
  { id: "10", title: "Heavy On My Heart", artist: "Lucki", display: "Heavy On My Heart - Lucki", clip: "clips/heavy-on-my-heart.mp3" },
  { id: "11", title: "I Know", artist: "Pradabagshawty", display: "I Know - Pradabagshawty", clip: "clips/i-knowp5.mp3" },
  { id: "12", title: "In The Air", artist: "Destroy Lonely", display: "In The Air - Destroy Lonely", clip: "clips/in-the-air.mp3" },
  { id: "13", title: "Just Score It", artist: "Osamason", display: "Just Score It - Osamason", clip: "clips/just-score-it.mp3" },
  { id: "14", title: "Louis V Everything", artist: "Autumn!", display: "Louis V Everything - Autumn!", clip: "clips/louis-v-everything.mp3" },
  { id: "15", title: "Need Me", artist: "Xaviersobased", display: "Need Me - Xaviersobased", clip: "clips/need-me.mp3" },
  { id: "16", title: "One Way", artist: "Autumn!", display: "One Way - Autumn!", clip: "clips/one-way.mp3" },
  { id: "17", title: "Racks Blue", artist: "Nine Vicious", display: "Racks Blue - Nine Vicious", clip: "clips/racks-blue.mp3" },
  { id: "18", title: "Relevant", artist: "Lil Uzi Vert", display: "Relevant - Lil Uzi Vert", clip: "clips/relevant.mp3" },
  { id: "19", title: "RIP", artist: "Playboi Carti", display: "RIP - Playboi Carti", clip: "clips/rip.mp3" },
  { id: "20", title: "Trenches", artist: "Osamason", display: "Trenches - Osamason", clip: "clips/trenches.mp3" },
  { id: "21", title: "WISHIN", artist: "Rexv2", display: "WISHIN - Rexv2", clip: "clips/WISHIN.mp3" },
  { id: "22", title: "Mona Lisa", artist: "Lucki", display: "Mona Lisa - Lucki", clip: "clips/mona-lisa.mp3" },
  { id: "23", title: "Can't Save Her", artist: "Lil Uzi Vert", display: "Can't Save Her - Lil Uzi Vert", clip: "clips/cant-save-her.mp3" },
  { id: "24", title: "Uh Oh, Thots!", artist: "Trippie Redd & XXXTENTACION", display: "Uh Oh, Thots! - Trippie Redd & XXXTENTACION", clip: "clips/uh-oh-thots.mp3" },
  { id: "25", title: "KYLIE!!!", artist: "Lucki", display: "KYLIE!!! - Lucki", clip: "clips/kylie.mp3" },
  { id: "26", title: "Marceline", artist: "Che", display: "Marceline - Che", clip: "clips/marceline.mp3" },
  { id: "27", title: "Trippple H", artist: "K Suave, Trippie Redd & D Savage", display: "Trippple H - K Suave, Trippie Redd & D Savage", clip: "clips/Trippple-H.mp3" },
  { id: "28", title: "Century", artist: "Esdeekid", display: "Century - Esdeekid", clip: "clips/century.mp3" },
  { id: "29", title: "Ref", artist: "Osamason", display: "Ref - Osamason", clip: "clips/ref.mp3" },
  { id: "30", title: "Die With Regret", artist: "Glokk40Spaz", display: "Die With Regret - Glokk40Spaz", clip: "clips/die-with-regret.mp3" },
  { id: "31", title: "Bad Man", artist: "Glokk40Spaz", display: "Bad Man - Glokk40Spaz", clip: "clips/bad-man.mp3" },
  { id: "32", title: "Them > You (Gotta Go!)", artist: "Autumn!", display: "Them > You (Gotta Go!) - Autumn!", clip: "clips/them-you.mp3" },
  { id: "33", title: "I Choose Violence", artist: "Glokk40Spaz", display: "I Choose Violence - Glokk40Spaz", clip: "clips/i-choose-violence.mp3" },
  { id: "34", title: "Sunset", artist: "Lucki", display: "Sunset - Lucki", clip: "clips/sunset.mp3" },
  { id: "35", title: "Randomly", artist: "Lucki", display: "Randomly - Lucki", clip: "clips/randomly.mp3" },
  { id: "36", title: "Leave Her", artist: "Lucki", display: "Leave Her - Lucki", clip: "clips/leave-her.mp3" },
  { id: "37", title: "Marble Floors", artist: "Summrs", display: "Marble Floors - Summrs", clip: "clips/marble-floors.mp3" },
  { id: "38", title: "Just Can't", artist: "Summrs", display: "Just Can't - Summrs", clip: "clips/just-cant.mp3" },
  { id: "39", title: "Swing Ya Pole", artist: "Summrs", display: "Swing Ya Pole - Summrs", clip: "clips/swing-ya-pole.mp3" },
  { id: "40", title: "Put Out Fye", artist: "Summrs", display: "Put Out Fye - Summrs", clip: "clips/put-out-fye.mp3" },
  { id: "41", title: "Unlimited", artist: "Lucki", display: "Unlimited - Lucki", clip: "clips/unlimited.mp3" },
  { id: "42", title: "Love Hate", artist: "Xaviersobased", display: "Love Hate - Xaviersobased", clip: "clips/love-hate.mp3" },
  { id: "43", title: "Double Whammy", artist: "Xaviersobased", display: "Double Whammy - Xaviersobased", clip: "clips/double-whammy.mp3" },
  { id: "44", title: "Special", artist: "Xaviersobased", display: "Special - Xaviersobased", clip: "clips/special.mp3" },
  { id: "45", title: "What Zit Tooya", artist: "Xaviersobased", display: "What Zit Tooya - Xaviersobased", clip: "clips/what-zit-tooya.mp3" },
  { id: "46", title: "Made Sum Plans", artist: "Osamason", display: "Made Sum Plans - Osamason", clip: "clips/made-sum-plans.mp3" },
  { id: "47", title: "Habits", artist: "Osamason", display: "Habits - Osamason", clip: "clips/habits.mp3" },
  { id: "48", title: "Ik What You Did Last Summer", artist: "Osamason", display: "Ik What You Did Last Summer - Osamason", clip: "clips/ikwydls.mp3" },
  { id: "49", title: "Pop", artist: "Osamason", display: "Pop - Osamason", clip: "clips/pop.mp3" },
  { id: "50", title: "Werkin", artist: "Osamason", display: "Werkin - Osamason", clip: "clips/werkin.mp3" },
  { id: "51", title: "If We Being Real", artist: "Yeat", display: "If We Being Real - Yeat", clip: "clips/if-we-being-real.mp3" },
  { id: "52", title: "Off Tha Lot", artist: "Yeat", display: "Off Tha Lot - Yeat", clip: "clips/off-tha-lot.mp3" },
  { id: "53", title: "Sorry Bout That", artist: "Yeat", display: "Sorry Bout That - Yeat", clip: "clips/sorry-bout-that.mp3" },
  { id: "54", title: "Poppin", artist: "Yeat", display: "Poppin - Yeat", clip: "clips/poppin.mp3" },
  { id: "55", title: "Nvr Again", artist: "Yeat", display: "Nvr Again - Yeat", clip: "clips/nvr-again.mp3" },
  { id: "56", title: "System", artist: "Yeat", display: "System - Yeat", clip: "clips/system.mp3" },
  { id: "57", title: "On Tha Line", artist: "Yeat", display: "On Tha Line - Yeat", clip: "clips/on-tha-line.mp3" },
  { id: "58", title: "Twizzy Rich", artist: "Yeat", display: "Twizzy Rich - Yeat", clip: "clips/twizzy-rich.mp3" },
  { id: "59", title: "Out The Way", artist: "Yeat", display: "Out The Way - Yeat", clip: "clips/out-the-way.mp3" },
  { id: "60", title: "Already Rich", artist: "Yeat", display: "Already Rich - Yeat", clip: "clips/already-rich.mp3" },
  { id: "61", title: "Turban", artist: "Yeat", display: "Turban - Yeat", clip: "clips/turban.mp3" },
  { id: "62", title: "Double", artist: "Yeat", display: "Double - Yeat", clip: "clips/double.mp3" },
  { id: "63", title: "Big Tonka", artist: "Yeat & Lil Uzi Vert", display: "Big Tonka - Yeat & Lil Uzi Vert", clip: "clips/big-tonka.mp3" },
  { id: "64", title: "Get Busy", artist: "Yeat", display: "Get Busy - Yeat", clip: "clips/get-busy.mp3" },
  { id: "65", title: "Still The Same", artist: "Autumn!", display: "Still The Same - Autumn!", clip: "clips/still-the-same.mp3" },
  { id: "66", title: "Can't Rent Anymore", artist: "Autumn!", display: "Can't Rent Anymore - Autumn!", clip: "clips/cant-rent-anymore.mp3" },
  { id: "67", title: "No New Friends", artist: "Autumn! & Summrs", display: "No New Friends - Autumn! & Summrs", clip: "clips/no-new-friends.mp3" },
  { id: "68", title: "My Collection", artist: "Autumn!", display: "My Collection - Autumn!", clip: "clips/my-collection.mp3" },
  { id: "69", title: "Bloods Always Thicker", artist: "Summrs", display: "Bloods Always Thicker - Summrs", clip: "clips/bloods-always-thicker.mp3" },
  { id: "70", title: "Fall Guys", artist: "Protect", display: "Fall Guys - Protect", clip: "clips/fall-guys.mp3" },
  { id: "71", title: "Two Chrome Necklaces", artist: "Autumn!", display: "Two Chrome Necklaces - Autumn!", clip: "clips/two-chrome-necklaces.mp3" },
  { id: "72", title: "Portrayal", artist: "Autumn!", display: "Portrayal - Autumn!", clip: "clips/portrayal.mp3" },
  { id: "73", title: "Probably", artist: "Autumn! & Yeat", display: "Probably - Autumn! & Yeat", clip: "clips/probably.mp3" },
  { id: "74", title: "The Way Life Goes", artist: "Lil Uzi Vert", display: "The Way Life Goes - Lil Uzi Vert", clip: "clips/the-way-life-goes.mp3" },
  { id: "75", title: "Homecoming", artist: "Lil Uzi Vert", display: "Homecoming - Lil Uzi Vert", clip: "clips/homecoming.mp3" },
  { id: "76", title: "Money Longer", artist: "Lil Uzi Vert", display: "Money Longer - Lil Uzi Vert", clip: "clips/money-longer.mp3" },
  { id: "77", title: "Erase Your Social", artist: "Lil Uzi Vert", display: "Erase Your Social - Lil Uzi Vert", clip: "clips/erase-your-social.mp3" },
  { id: "78", title: "We Good", artist: "Lil Uzi Vert", display: "We Good - Lil Uzi Vert", clip: "clips/we-good.mp3" },
  { id: "79", title: "Feelings Mutual", artist: "Lil Uzi Vert", display: "Feelings Mutual - Lil Uzi Vert", clip: "clips/feelings-mutual.mp3" },
  { id: "80", title: "How To Talk", artist: "Lil Uzi Vert", display: "How To Talk - Lil Uzi Vert", clip: "clips/how-to-talk.mp3" },
  { id: "81", title: "Team Rocket", artist: "Lil Uzi Vert", display: "Team Rocket - Lil Uzi Vert", clip: "clips/team-rocket.mp3" },
  { id: "82", title: "14", artist: "BabySantana & Ka$hdami", display: "14 - BabySantana & Ka$hdami", clip: "clips/14.mp3" },
  { id: "83", title: "2019", artist: "Lucki", display: "2019 - Lucki", clip: "clips/2019.mp3" },
  { id: "84", title: "How Does It Feel", artist: "D Savage", display: "How Does It Feel - D Savage", clip: "clips/how-does-it-feel.mp3" },
  { id: "85", title: "Lo Mein", artist: "Lil Uzi Vert", display: "Lo Mein - Lil Uzi Vert", clip: "clips/lo-mein.mp3" },
  { id: "86", title: "Prices", artist: "Lil Uzi Vert", display: "Prices - Lil Uzi Vert", clip: "clips/prices.mp3" },
  { id: "87", title: "16*29", artist: "Lil Uzi Vert & Playboi Carti", display: "16*29 - Lil Uzi Vert & Playboi Carti", clip: "clips/1629.mp3" },
  { id: "88", title: "Life Goes On", artist: "Lil Baby, Gunna & Lil Uzi Vert", display: "Life Goes On - Lil Baby, Gunna & Lil Uzi Vert", clip: "clips/life-goes-on.mp3" },
  { id: "89", title: "You Was Right", artist: "Lil Uzi Vert", display: "You Was Right - Lil Uzi Vert", clip: "clips/you-was-right.mp3" },
  { id: "90", title: "Green Room", artist: "Ken Carson", display: "Green Room - Ken Carson", clip: "clips/green-room.mp3" },
  { id: "91", title: "I Know", artist: "D Savage", display: "I Know - D Savage", clip: "clips/iknowds.mp3" },
  { id: "92", title: "Shoota", artist: "Playboi Carti & Lil Uzi Vert", display: "Shoota - Playboi Carti & Lil Uzi Vert", clip: "clips/shoota.mp3" },
  { id: "93", title: "Fell In Luv", artist: "Playboi Carti & Bryson Tiller", display: "Fell In Luv - Playboi Carti & Bryson Tiller", clip: "clips/fell-in-luv.mp3" },
  { id: "94", title: "Long Time", artist: "Playboi Carti", display: "Long Time - Playboi Carti", clip: "clips/long-time.mp3" },
  { id: "95", title: "Foreign", artist: "Playboi Carti", display: "Foreign - Playboi Carti", clip: "clips/foreign.mp3" },
  { id: "96", title: "FlatBed Freestyle", artist: "Playboi Carti", display: "FlatBed Freestyle - Playboi Carti", clip: "clips/flatbed-freestyle.mp3" },
  { id: "97", title: "Over", artist: "Playboi Carti", display: "Over - Playboi Carti", clip: "clips/over.mp3" },
  { id: "98", title: "ILoveUIHateU", artist: "Playboi Carti", display: "ILoveUIHateU - Playboi Carti", clip: "clips/iloveuihateu.mp3" },
  { id: "99", title: "New Tank", artist: "Playboi Carti", display: "New Tank - Playboi Carti", clip: "clips/new-tank.mp3" },
  { id: "100", title: "Meh", artist: "Playboi Carti", display: "Meh - Playboi Carti", clip: "clips/meh.mp3" },
  { id: "101", title: "Antisocial", artist: "BabySantana & Slump6s", display: "Antisocial - BabySantana & Slump6s", clip: "clips/antisocial.mp3" },
  { id: "102", title: "Antisocial 2", artist: "BabySantana, Slump6s, Yung Fazo, Xhulooo & SSGKobe", display: "Antisocial 2 - BabySantana, Slump6s, Yung Fazo, Xhulooo & SSGKobe", clip: "clips/antisocial-2.mp3" }
];
